[build]
builder = "nixpacks"
buildCommand = "npm run db:generate && npm run build"

[build.nixpacks]
nixPkgs = ["nodejs_20", "npm-10_x", "openssl"]

[deploy]
startCommand = "npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
