[build]
builder = "nixpacks"
buildCommand = "npm run db:generate && npx prisma db push && npm run build"

[build.nixpacks]
nixPkgs = ["nodejs_20", "npm-10_x", "openssl"]

[deploy]
startCommand = "npm run start -- -p ${PORT:-3000}"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
